DROP DATABASE STUDENTDB;
CREATE DATABASE  STUDENTDB;
USE STUDENTDB;

CREATE TABLE STUDENT(
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(100) 	NOT NULL,
    STUDENT_CODE VARCHAR(50)	NOT NULL,
    UNIQUE (STUDENT_CODE)
);
CREATE TABLE STUDENT_INFO(
	INFO_ID 	INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_ID 	INT 			NOT NULL,
    ADDRESS 	VARCHAR(200) 	NOT NULL,
    AVERAGE_SCORE 	DOUBLE 		NOT NULL,
    DATE_OF_BIRTH 	DATE  NOT NULL
);
ALTER TABLE STUDENT_INFO ADD FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);
	 	/* */
		SELECT 
  	  		STUDENT.STUDENT_ID,
  	  		STUDENT.STUDENT_NAME,
  	  		STUDENT.STUDENT_CODE,
  	  		STUDENT_INFO.ADDRESS,
  	  		STUDENT_INFO.AVERAGE_SCORE,
  	  		STUDENT_INFO.DATE_OF_BIRTH
  	 	FROM 
  	  		STUDENT ,
            STUDENT_INFO 
		ON STUDENT.STUDENT_ID = STUDENT_INFO.STUDENT_ID
		
	
/*INSERT DATA*/
SELECT STUDENT_NAME FROM STUDENT;
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','13A1519597');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','13115S8127');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','1D11A97');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','131A5F887');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','C1519597');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','1311S87');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','1D519597');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','131151F87');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','13G1519597');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','1311H887');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','121311');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','13115C7');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','1D1D97');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','131S7');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','C1G97');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','13AS87');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Nguyễn Văn Linh','1D51G97');
INSERT INTO STUDENT(STUDENT_NAME,STUDENT_CODE) VALUES('Dư Ngọc Kim','13115K7');
/*INSERT DATA*/
INSERT INTO STUDENT_INFO(STUDENT_ID,ADDRESS,AVERAGE_SCORE,DATE_OF_BIRTH) VALUES(1,'Quận 12',9.5,'1995-02-16');
INSERT INTO STUDENT_INFO(STUDENT_ID,ADDRESS,AVERAGE_SCORE,DATE_OF_BIRTH) VALUES(2,'Quận 12',9,'1995-08-16');