CREATE DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO
CREATE TABLE SINHVIEN (
	MSSV	INT PRIMARY KEY (MSSV),
	NAME	NVARCHAR (50)	NOT NULL,
	CLASS	VARCHAR  (30)	NOT NULL,
	ADREESS NVARCHAR (50)	NOT NULL
	
 ) 
GO
INSERT INTO  SINHVIEN  VALUES (1311519597,N'Nguyễn Văn Linh','13DTH02',N'Quận 12') ;
INSERT INTO  SINHVIEN  VALUES (1311518587,N'Dư Ngọc Kim','13DTH02',N'Tân Bình');
INSERT INTO  SINHVIEN  VALUES (100,N'Đặng Tường Minh','13DTH02',N'Quận 1');
INSERT INTO  SINHVIEN  VALUES (111,N'Nguyễn Thị Thuyết','13DTH02',N'Quận 14');
INSERT INTO  SINHVIEN  VALUES (112,N'Lý Trường Khải','13DTH02',N'Quận 17');
SELECT * FROM SINHVIEN